//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using BlogTemplate.Infrastructure.Kentico.Xperience.Abstractions.PageTypes;
using CMS;
using CMS.Base;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.Helpers;

[assembly: RegisterDocumentType( AuthorNode.CLASS_NAME, typeof( AuthorNode ) )]

namespace BlogTemplate.Infrastructure.Kentico.Xperience.Abstractions.PageTypes
{
    /// <summary>
    /// Represents a content item of type AuthorNode.
    /// </summary>
    public partial class AuthorNode : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "BlogTemplate.AuthorNode";


        /// <summary>
        /// The instance of the class that provides extended API for working with AuthorNode fields.
        /// </summary>
        private readonly AuthorNodeFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// AuthorNodeID.
        /// </summary>
        [DatabaseIDField]
        public int AuthorNodeID
        {
            get
            {
                return ValidationHelper.GetInteger( GetValue( "AuthorNodeID" ), 0 );
            }
            set
            {
                SetValue( "AuthorNodeID", value );
            }
        }


        /// <summary>
        /// Image.
        /// </summary>
        [DatabaseField]
        public string Image
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "Image" ), @"" );
            }
            set
            {
                SetValue( "Image", value );
            }
        }


        /// <summary>
        /// Description.
        /// </summary>
        [DatabaseField]
        public string Description
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "Description" ), @"" );
            }
            set
            {
                SetValue( "Description", value );
            }
        }


        /// <summary>
        /// Twitter.
        /// </summary>
        [DatabaseField]
        public string TwitterUrl
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "TwitterUrl" ), @"" );
            }
            set
            {
                SetValue( "TwitterUrl", value );
            }
        }


        /// <summary>
        /// Facebook.
        /// </summary>
        [DatabaseField]
        public string FacebookUrl
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "FacebookUrl" ), @"" );
            }
            set
            {
                SetValue( "FacebookUrl", value );
            }
        }


        /// <summary>
        /// GitHub.
        /// </summary>
        [DatabaseField]
        public string GitHubUrl
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "GitHubUrl" ), @"" );
            }
            set
            {
                SetValue( "GitHubUrl", value );
            }
        }


        /// <summary>
        /// Title.
        /// </summary>
        [DatabaseField]
        public string OpenGraphTitle
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "OpenGraphTitle" ), @"" );
            }
            set
            {
                SetValue( "OpenGraphTitle", value );
            }
        }


        /// <summary>
        /// Description.
        /// </summary>
        [DatabaseField]
        public string OpenGraphDescription
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "OpenGraphDescription" ), @"" );
            }
            set
            {
                SetValue( "OpenGraphDescription", value );
            }
        }


        /// <summary>
        /// Image.
        /// </summary>
        [DatabaseField]
        public string OpenGraphImage
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "OpenGraphImage" ), @"" );
            }
            set
            {
                SetValue( "OpenGraphImage", value );
            }
        }


        /// <summary>
        /// Video.
        /// </summary>
        [DatabaseField]
        public string OpenGraphVideo
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "OpenGraphVideo" ), @"" );
            }
            set
            {
                SetValue( "OpenGraphVideo", value );
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with AuthorNode fields.
        /// </summary>
        [RegisterProperty]
        public AuthorNodeFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with AuthorNode fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class AuthorNodeFields : AbstractHierarchicalObject<AuthorNodeFields>
        {
            /// <summary>
            /// The content item of type AuthorNode that is a target of the extended API.
            /// </summary>
            private readonly AuthorNode mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="AuthorNodeFields" /> class with the specified content item of type AuthorNode.
            /// </summary>
            /// <param name="instance">The content item of type AuthorNode that is a target of the extended API.</param>
            public AuthorNodeFields( AuthorNode instance )
            {
                mInstance = instance;
            }


            /// <summary>
            /// AuthorNodeID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.AuthorNodeID;
                }
                set
                {
                    mInstance.AuthorNodeID = value;
                }
            }


            /// <summary>
            /// Image.
            /// </summary>
            public string Image
            {
                get
                {
                    return mInstance.Image;
                }
                set
                {
                    mInstance.Image = value;
                }
            }


            /// <summary>
            /// Description.
            /// </summary>
            public string Description
            {
                get
                {
                    return mInstance.Description;
                }
                set
                {
                    mInstance.Description = value;
                }
            }


            /// <summary>
            /// Twitter.
            /// </summary>
            public string TwitterUrl
            {
                get
                {
                    return mInstance.TwitterUrl;
                }
                set
                {
                    mInstance.TwitterUrl = value;
                }
            }


            /// <summary>
            /// Facebook.
            /// </summary>
            public string FacebookUrl
            {
                get
                {
                    return mInstance.FacebookUrl;
                }
                set
                {
                    mInstance.FacebookUrl = value;
                }
            }


            /// <summary>
            /// GitHub.
            /// </summary>
            public string GitHubUrl
            {
                get
                {
                    return mInstance.GitHubUrl;
                }
                set
                {
                    mInstance.GitHubUrl = value;
                }
            }


            /// <summary>
            /// Title.
            /// </summary>
            public string OpenGraphTitle
            {
                get
                {
                    return mInstance.OpenGraphTitle;
                }
                set
                {
                    mInstance.OpenGraphTitle = value;
                }
            }


            /// <summary>
            /// Description.
            /// </summary>
            public string OpenGraphDescription
            {
                get
                {
                    return mInstance.OpenGraphDescription;
                }
                set
                {
                    mInstance.OpenGraphDescription = value;
                }
            }


            /// <summary>
            /// Image.
            /// </summary>
            public string OpenGraphImage
            {
                get
                {
                    return mInstance.OpenGraphImage;
                }
                set
                {
                    mInstance.OpenGraphImage = value;
                }
            }


            /// <summary>
            /// Video.
            /// </summary>
            public string OpenGraphVideo
            {
                get
                {
                    return mInstance.OpenGraphVideo;
                }
                set
                {
                    mInstance.OpenGraphVideo = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="AuthorNode" /> class.
        /// </summary>
        public AuthorNode( ) : base( CLASS_NAME )
        {
            mFields = new AuthorNodeFields( this );
        }

        #endregion
    }
}
