# This pipeline creates an artifact of a runnable Mvc site if the Blog Template

name: $(Date:yyyyMMdd)$(Rev:-r)
pool:
  vmImage: "windows-latest"

pr:
  branches:
    include:
      - develop
      - feature/*

trigger:
  branches:
    include:
      - main
      - develop

steps:
  - task: DotNetCoreCLI@2
    displayName: "restore dependencies"
    inputs:
      command: "restore"
      projects: "src/src/Mvc/App/BlogTemplate.Mvc.App.csproj"

  # NOTE: MSBuild executes npm build tasks for us
  - task: DotNetCoreCLI@2
    displayName: "build mvc"
    inputs:
      command: "build"
      projects: "src/src/Mvc/App/BlogTemplate.Mvc.App.csproj"
      arguments: "-c Release --no-restore"

  - task: DotNetCoreCLI@2
    displayName: "create deployable"
    inputs:
      command: "publish"
      publishWebProjects: false
      projects: "src/src/Mvc/App/BlogTemplate.Mvc.App.csproj"
      arguments: '-c Release -o "$(build.artifactstagingdirectory)" --no-build'

  # TODO: add appsettings.bzs-dev.json to mvc artifact from DevOps Secrets

  - task: PublishBuildArtifacts@1
    displayName: "publish artifact"
    inputs:
      PathtoPublish: "$(build.artifactstagingdirectory)"
      ArtifactName: "blogtemplate-mvc"
