# This pipeline builds an artifact of a publishable .NET Core CLI Template NuGet package

name: $(Date:yyyyMMdd)$(Rev:-r)
pool:
  vmImage: "windows-latest"

pr:
  branches:
    include:
      - develop
      - feature/*

trigger:
  branches:
    include:
      - main
      - develop

steps:
  - task: DotNetCoreCLI@2
    displayName: "create deployable"
    inputs:
      command: "pack"
      projects: "src/Mvc/App/BlogTemplate.Mvc.App.csproj"
      arguments: '-o "$(build.artifactstagingdirectory)" --no-build'

  - task: PublishBuildArtifacts@1
    displayName: "publish artifact"
    inputs:
      PathtoPublish: "$(build.artifactstagingdirectory)"
      ArtifactName: "blogtemplate-package"
