//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using BlogTemplate.Infrastructure.Xperience.Abstractions.PageTypes;
using CMS;
using CMS.Base;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.Helpers;

[assembly: RegisterDocumentType( ArticleNode.CLASS_NAME, typeof( ArticleNode ) )]

namespace BlogTemplate.Infrastructure.Xperience.Abstractions.PageTypes
{
    /// <summary>
    /// Represents a content item of type ArticleNode.
    /// </summary>
    public partial class ArticleNode : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "BlogTemplate.ArticleNode";


        /// <summary>
        /// The instance of the class that provides extended API for working with ArticleNode fields.
        /// </summary>
        private readonly ArticleNodeFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// ArticleNodeID.
        /// </summary>
        [DatabaseIDField]
        public int ArticleNodeID
        {
            get
            {
                return ValidationHelper.GetInteger( GetValue( "ArticleNodeID" ), 0 );
            }
            set
            {
                SetValue( "ArticleNodeID", value );
            }
        }


        /// <summary>
        /// Summary.
        /// </summary>
        [DatabaseField]
        public string Summary
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "Summary" ), @"" );
            }
            set
            {
                SetValue( "Summary", value );
            }
        }


        /// <summary>
        /// Author.
        /// </summary>
        [DatabaseField]
        public Guid AuthorGuid
        {
            get
            {
                return ValidationHelper.GetGuid( GetValue( "AuthorGuid" ), Guid.Empty );
            }
            set
            {
                SetValue( "AuthorGuid", value );
            }
        }


        /// <summary>
        /// Hero Image.
        /// </summary>
        [DatabaseField]
        public string HeroImage
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "HeroImage" ), @"" );
            }
            set
            {
                SetValue( "HeroImage", value );
            }
        }


        /// <summary>
        /// Content.
        /// </summary>
        [DatabaseField]
        public string Content
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "Content" ), @"" );
            }
            set
            {
                SetValue( "Content", value );
            }
        }


        /// <summary>
        /// Title.
        /// </summary>
        [DatabaseField]
        public string OpenGraphTitle
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "OpenGraphTitle" ), @"" );
            }
            set
            {
                SetValue( "OpenGraphTitle", value );
            }
        }


        /// <summary>
        /// Description.
        /// </summary>
        [DatabaseField]
        public string OpenGraphDescription
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "OpenGraphDescription" ), @"" );
            }
            set
            {
                SetValue( "OpenGraphDescription", value );
            }
        }


        /// <summary>
        /// Image.
        /// </summary>
        [DatabaseField]
        public string OpenGraphImage
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "OpenGraphImage" ), @"" );
            }
            set
            {
                SetValue( "OpenGraphImage", value );
            }
        }


        /// <summary>
        /// Video.
        /// </summary>
        [DatabaseField]
        public string OpenGraphVideo
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "OpenGraphVideo" ), @"" );
            }
            set
            {
                SetValue( "OpenGraphVideo", value );
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with ArticleNode fields.
        /// </summary>
        [RegisterProperty]
        public ArticleNodeFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with ArticleNode fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class ArticleNodeFields : AbstractHierarchicalObject<ArticleNodeFields>
        {
            /// <summary>
            /// The content item of type ArticleNode that is a target of the extended API.
            /// </summary>
            private readonly ArticleNode mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="ArticleNodeFields" /> class with the specified content item of type ArticleNode.
            /// </summary>
            /// <param name="instance">The content item of type ArticleNode that is a target of the extended API.</param>
            public ArticleNodeFields( ArticleNode instance )
            {
                mInstance = instance;
            }


            /// <summary>
            /// ArticleNodeID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.ArticleNodeID;
                }
                set
                {
                    mInstance.ArticleNodeID = value;
                }
            }


            /// <summary>
            /// Summary.
            /// </summary>
            public string Summary
            {
                get
                {
                    return mInstance.Summary;
                }
                set
                {
                    mInstance.Summary = value;
                }
            }


            /// <summary>
            /// Author.
            /// </summary>
            public Guid AuthorGuid
            {
                get
                {
                    return mInstance.AuthorGuid;
                }
                set
                {
                    mInstance.AuthorGuid = value;
                }
            }


            /// <summary>
            /// Hero Image.
            /// </summary>
            public string HeroImage
            {
                get
                {
                    return mInstance.HeroImage;
                }
                set
                {
                    mInstance.HeroImage = value;
                }
            }


            /// <summary>
            /// Content.
            /// </summary>
            public string Content
            {
                get
                {
                    return mInstance.Content;
                }
                set
                {
                    mInstance.Content = value;
                }
            }


            /// <summary>
            /// Title.
            /// </summary>
            public string OpenGraphTitle
            {
                get
                {
                    return mInstance.OpenGraphTitle;
                }
                set
                {
                    mInstance.OpenGraphTitle = value;
                }
            }


            /// <summary>
            /// Description.
            /// </summary>
            public string OpenGraphDescription
            {
                get
                {
                    return mInstance.OpenGraphDescription;
                }
                set
                {
                    mInstance.OpenGraphDescription = value;
                }
            }


            /// <summary>
            /// Image.
            /// </summary>
            public string OpenGraphImage
            {
                get
                {
                    return mInstance.OpenGraphImage;
                }
                set
                {
                    mInstance.OpenGraphImage = value;
                }
            }


            /// <summary>
            /// Video.
            /// </summary>
            public string OpenGraphVideo
            {
                get
                {
                    return mInstance.OpenGraphVideo;
                }
                set
                {
                    mInstance.OpenGraphVideo = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="ArticleNode" /> class.
        /// </summary>
        public ArticleNode( ) : base( CLASS_NAME )
        {
            mFields = new ArticleNodeFields( this );
        }

        #endregion
    }
}
