//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using BlogTemplate.Infrastructure.Xperience.Abstractions.PageTypes;
using CMS;
using CMS.Base;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.Helpers;

[assembly: RegisterDocumentType( BaseNode.CLASS_NAME, typeof( BaseNode ) )]

namespace BlogTemplate.Infrastructure.Xperience.Abstractions.PageTypes
{
    /// <summary>
    /// Represents a content item of type BaseNode.
    /// </summary>
    public partial class BaseNode : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "BlogTemplate.BaseNode";


        /// <summary>
        /// The instance of the class that provides extended API for working with BaseNode fields.
        /// </summary>
        private readonly BaseNodeFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// BaseNodeID.
        /// </summary>
        [DatabaseIDField]
        public int BaseNodeID
        {
            get
            {
                return ValidationHelper.GetInteger( GetValue( "BaseNodeID" ), 0 );
            }
            set
            {
                SetValue( "BaseNodeID", value );
            }
        }


        /// <summary>
        /// Title.
        /// </summary>
        [DatabaseField]
        public string OpenGraphTitle
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "OpenGraphTitle" ), @"" );
            }
            set
            {
                SetValue( "OpenGraphTitle", value );
            }
        }


        /// <summary>
        /// Description.
        /// </summary>
        [DatabaseField]
        public string OpenGraphDescription
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "OpenGraphDescription" ), @"" );
            }
            set
            {
                SetValue( "OpenGraphDescription", value );
            }
        }


        /// <summary>
        /// Image.
        /// </summary>
        [DatabaseField]
        public string OpenGraphImage
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "OpenGraphImage" ), @"" );
            }
            set
            {
                SetValue( "OpenGraphImage", value );
            }
        }


        /// <summary>
        /// Video.
        /// </summary>
        [DatabaseField]
        public string OpenGraphVideo
        {
            get
            {
                return ValidationHelper.GetString( GetValue( "OpenGraphVideo" ), @"" );
            }
            set
            {
                SetValue( "OpenGraphVideo", value );
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with BaseNode fields.
        /// </summary>
        [RegisterProperty]
        public BaseNodeFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with BaseNode fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class BaseNodeFields : AbstractHierarchicalObject<BaseNodeFields>
        {
            /// <summary>
            /// The content item of type BaseNode that is a target of the extended API.
            /// </summary>
            private readonly BaseNode mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="BaseNodeFields" /> class with the specified content item of type BaseNode.
            /// </summary>
            /// <param name="instance">The content item of type BaseNode that is a target of the extended API.</param>
            public BaseNodeFields( BaseNode instance )
            {
                mInstance = instance;
            }


            /// <summary>
            /// BaseNodeID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.BaseNodeID;
                }
                set
                {
                    mInstance.BaseNodeID = value;
                }
            }


            /// <summary>
            /// Title.
            /// </summary>
            public string OpenGraphTitle
            {
                get
                {
                    return mInstance.OpenGraphTitle;
                }
                set
                {
                    mInstance.OpenGraphTitle = value;
                }
            }


            /// <summary>
            /// Description.
            /// </summary>
            public string OpenGraphDescription
            {
                get
                {
                    return mInstance.OpenGraphDescription;
                }
                set
                {
                    mInstance.OpenGraphDescription = value;
                }
            }


            /// <summary>
            /// Image.
            /// </summary>
            public string OpenGraphImage
            {
                get
                {
                    return mInstance.OpenGraphImage;
                }
                set
                {
                    mInstance.OpenGraphImage = value;
                }
            }


            /// <summary>
            /// Video.
            /// </summary>
            public string OpenGraphVideo
            {
                get
                {
                    return mInstance.OpenGraphVideo;
                }
                set
                {
                    mInstance.OpenGraphVideo = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="BaseNode" /> class.
        /// </summary>
        public BaseNode( ) : base( CLASS_NAME )
        {
            mFields = new BaseNodeFields( this );
        }

        #endregion
    }
}
