//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using BlogTemplate.Infrastructure.Kentico.Xperience.Abstractions.PageTypes;

[assembly: RegisterDocumentType( AboutNode.CLASS_NAME, typeof( AboutNode ) )]

namespace BlogTemplate.Infrastructure.Kentico.Xperience.Abstractions.PageTypes
{
    /// <summary>
    /// Represents a content item of type AboutNode.
    /// </summary>
    public partial class AboutNode : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "BlogTemplate.AboutNode";


        /// <summary>
        /// The instance of the class that provides extended API for working with AboutNode fields.
        /// </summary>
        private readonly AboutNodeFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// AboutNodeID.
        /// </summary>
        [DatabaseIDField]
        public int AboutNodeID {
            get
            {
                return ValidationHelper.GetInteger( GetValue( "AboutNodeID" ), 0 );
            }
            set
            {
                SetValue( "AboutNodeID", value );
            }
        }


        /// <summary>
        /// Title.
        /// </summary>
        [DatabaseField]
        public string OpenGraphTitle {
            get
            {
                return ValidationHelper.GetString( GetValue( "OpenGraphTitle" ), @"" );
            }
            set
            {
                SetValue( "OpenGraphTitle", value );
            }
        }


        /// <summary>
        /// Description.
        /// </summary>
        [DatabaseField]
        public string OpenGraphDescription {
            get
            {
                return ValidationHelper.GetString( GetValue( "OpenGraphDescription" ), @"" );
            }
            set
            {
                SetValue( "OpenGraphDescription", value );
            }
        }


        /// <summary>
        /// Image.
        /// </summary>
        [DatabaseField]
        public string OpenGraphImage {
            get
            {
                return ValidationHelper.GetString( GetValue( "OpenGraphImage" ), @"" );
            }
            set
            {
                SetValue( "OpenGraphImage", value );
            }
        }


        /// <summary>
        /// Video.
        /// </summary>
        [DatabaseField]
        public string OpenGraphVideo {
            get
            {
                return ValidationHelper.GetString( GetValue( "OpenGraphVideo" ), @"" );
            }
            set
            {
                SetValue( "OpenGraphVideo", value );
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with AboutNode fields.
        /// </summary>
        [RegisterProperty]
        public AboutNodeFields Fields {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with AboutNode fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class AboutNodeFields : AbstractHierarchicalObject<AboutNodeFields>
        {
            /// <summary>
            /// The content item of type AboutNode that is a target of the extended API.
            /// </summary>
            private readonly AboutNode mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="AboutNodeFields" /> class with the specified content item of type AboutNode.
            /// </summary>
            /// <param name="instance">The content item of type AboutNode that is a target of the extended API.</param>
            public AboutNodeFields( AboutNode instance )
            {
                mInstance = instance;
            }


            /// <summary>
            /// AboutNodeID.
            /// </summary>
            public int ID {
                get
                {
                    return mInstance.AboutNodeID;
                }
                set
                {
                    mInstance.AboutNodeID = value;
                }
            }


            /// <summary>
            /// Title.
            /// </summary>
            public string OpenGraphTitle {
                get
                {
                    return mInstance.OpenGraphTitle;
                }
                set
                {
                    mInstance.OpenGraphTitle = value;
                }
            }


            /// <summary>
            /// Description.
            /// </summary>
            public string OpenGraphDescription {
                get
                {
                    return mInstance.OpenGraphDescription;
                }
                set
                {
                    mInstance.OpenGraphDescription = value;
                }
            }


            /// <summary>
            /// Image.
            /// </summary>
            public string OpenGraphImage {
                get
                {
                    return mInstance.OpenGraphImage;
                }
                set
                {
                    mInstance.OpenGraphImage = value;
                }
            }


            /// <summary>
            /// Video.
            /// </summary>
            public string OpenGraphVideo {
                get
                {
                    return mInstance.OpenGraphVideo;
                }
                set
                {
                    mInstance.OpenGraphVideo = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="AboutNode" /> class.
        /// </summary>
        public AboutNode( ) : base( CLASS_NAME )
        {
            mFields = new AboutNodeFields( this );
        }

        #endregion
    }
}
